config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :playlists

  resources :songs
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include UsersHelper
  def index
  	@user = User.new
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
    @user = current_user
  	respond_to do |format|
      @new_playlist = Playlist.new(params[:name],params[:user_id])
  		format.js
      redirect_to users_path
  	end
  end

  def update

  end

  def delete
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def update
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def index
    @user = current_user
    @playlists = show_playlists
  end

  def show
  end

  def new
  end

  def update
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource 
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def logged_in
		if current_user
			current_user
		else
			User.new
		end
	end
	def show_playlists
		if Playlist.all 
			Playlist.all
		else
			Playlist.new
		end
	end
end

app/views/home/index.html.erb
index home

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JUKE BOX</title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <h4>Juke Box</h4>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"> 
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <% if !current_user %>
            <div class="nav-item">
              <ul class="dropdown test1">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" aria-haspopup="true" aria-expanded="false">Sign Up/Sign In</button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
                  <div class="card" style="width: 20rem;">
                    <div class="card-block">
                      <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                          <a class="nav-link active" data-toggle="tab" href="#users_signup" role="tab" aria-controls="users_signup">sign up</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" data-toggle="tab" href="#users_signin" role="tab" aria-controls="users_signin">sign in</a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="tab-pane active" id="users_signup" role="tabpanel"><%= render 'users/registrations/new' %></div>
                        <div class="tab-pane" id="users_signin" role="tabpanel"><%= render 'users/sessions/new' %></div>
                      </div>
                    </div>
                  </div>
                </div>
              </ul>
            </div>
          <% else %>
            <ul class="nav-item active">
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/create.js.erb
$('.ShowPlayList').html("<h1>Songs</h1><%= j render 'songs' %><hr>");

app/views/playlists/delete.html.erb
<h1>Playlists#delete</h1>
<p>Find me in app/views/playlists/delete.html.erb</p>

app/views/playlists/update.html.erb
<h1>Playlists#update</h1>
<p>Find me in app/views/playlists/update.html.erb</p>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/delete.html.erb
<h1>Songs#delete</h1>
<p>Find me in app/views/songs/delete.html.erb</p>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>

app/views/songs/update.html.erb
<h1>Songs#update</h1>
<p>Find me in app/views/songs/update.html.erb</p>

app/views/users/_showing_playlists.html.erb
<% @playlists.each do |playlist| %>
	<h4><%= playlist.name %> </h4>
<% end %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h2>Welcome <%= @user.email %> </h2>
<div class='container'>
    <div class="menue">
        
    </div>
    <div class='leftMenue'>
        <h4 class='addSongTitle' >Add Song To Playlist</h4>
        <hr>
        <div class='searchResults'>
        </div>
        
    </div>
    <div class='currentSong'>
          
    </div> 
    <div class=rightMenue>
        <div class='playListInfo'>
            <h4 class='addPlayLists'>Add New Playlist</h4><br><hr>
            <%= form_tag playlists_path, remote: true do %>
                <%= hidden_field_tag :user_id, @user.id %>
                <%= search_field_tag :name %>
                <%= submit_tag "Add" %>
            <% end %>
            <div class='addToPlayList'>
                <%= render 'showing_playlists' %>
            </div>
        </div>
    </div>
</div>

<div class='audioFiles'>
	<audio src="" class="songPlace"> 
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>